"""Download the Material Design Icons used by the preview and write icons.js.

The preview has to work offline, so the icon paths are vendored next to it
instead of being pulled from a CDN at runtime.

    python dashboards/preview/fetch_icons.py
"""

from __future__ import annotations

import json
import pathlib
import re
import urllib.request

VERSION = "7.4.47"
BASE = f"https://cdn.jsdelivr.net/npm/@mdi/svg@{VERSION}/svg"

ICONS = [
    "account-hard-hat",
    "alert-circle-outline",
    "alert-outline",
    "arrow-left-bold-outline",
    "barcode",
    "bell-ring-outline",
    "chart-bell-curve",
    "chart-bell-curve-cumulative",
    "chart-line",
    "chart-timeline-variant",
    "chip",
    "clock-outline",
    "cog",
    "cog-outline",
    "eye-outline",
    "home-thermometer",
    "information-outline",
    "key-variant",
    "minus",
    "network",
    "plus",
    "pump",
    "radiator",
    "scale-balance",
    "snowflake",
    "speedometer-slow",
    "stethoscope",
    "thermometer",
    "thermometer-auto",
    "thermometer-check",
    "thermometer-low",
    "timer",
    "timer-refresh",
    "timer-refresh-outline",
    "tune-variant",
    "valve",
    "valve-closed",
    "valve-open",
    "water-boiler",
    "weather-sunny-off",
]

PATH_RE = re.compile(r'<path d="([^"]+)"')


def main() -> int:
    out = pathlib.Path(__file__).resolve().parent / "icons.js"
    paths: dict[str, str] = {}
    for name in ICONS:
        with urllib.request.urlopen(f"{BASE}/{name}.svg", timeout=30) as response:
            body = response.read().decode("utf-8")
        match = PATH_RE.search(body)
        if not match:
            print(f"!! no path in {name}")
            continue
        paths[name] = match.group(1)
        print(f"ok {name} ({len(match.group(1))} chars)")

    payload = (
        "// Generated by dashboards/preview/fetch_icons.py - do not edit.\n"
        f"// Material Design Icons {VERSION} (@mdi/svg), MIT licence.\n"
        "window.MDI = "
        + json.dumps(paths, indent=2, ensure_ascii=True)
        + ";\n"
    )
    out.write_text(payload, encoding="utf-8", newline="\n")
    print(f"\nwrote {out} ({len(paths)} icons, {len(payload)} bytes)")
    return 0 if len(paths) == len(ICONS) else 1


if __name__ == "__main__":
    raise SystemExit(main())
